2023-11-27T04:04:03+0000	[-] Python Version 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]	Unnamed: 2	Unnamed: 3	Unnamed: 4
2023-11-27T23:37:32+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] outgoing: b'aes256-ctr' b'hmac-sha2-256' b'none'			
2023-11-27T23:37:32+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] incoming: b'aes256-ctr' b'hmac-sha2-256' b'none'			
2023-11-27T23:37:32+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] NEW KEYS			
2023-11-27T23:37:32+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] starting service b'ssh-userauth'			
2023-11-27T23:37:33+0000	[cowrie.ssh.userauth.HoneyPotSSHUserAuthServer#debug] b'root' trying auth b'none'			
2023-11-27T23:37:36+0000	[cowrie.ssh.userauth.HoneyPotSSHUserAuthServer#debug] b'root' trying auth b'password'			
2023-11-27T23:37:36+0000	[HoneyPotSSHTransport,0,148.100.184.198] Could not read etc/userdb.txt, default database activated			
2023-11-27T23:37:36+0000	[HoneyPotSSHTransport,0,148.100.184.198] login attempt [b'root'/b'admin'] succeeded			
2023-11-27T23:37:36+0000	[HoneyPotSSHTransport,0,148.100.184.198] Initialized emulated server as architecture: linux-x64-lsb			
2023-11-27T23:37:36+0000	[cowrie.ssh.userauth.HoneyPotSSHUserAuthServer#debug] b'root' authenticated with b'password'			
2023-11-27T23:37:36+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] starting service b'ssh-connection'			
2023-11-27T23:37:36+0000	[cowrie.ssh.connection.CowrieSSHConnection#debug] got channel b'session' request			
2023-11-27T23:37:36+0000	[cowrie.ssh.session.HoneyPotSSHSession#info] channel open			
2023-11-27T23:37:36+0000	[twisted.conch.ssh.session#info] Handling pty request: b'xterm' (24, 80, 0, 0)			
2023-11-27T23:37:36+0000	[SSHChannel session (0) on SSHService b'ssh-connection' on HoneyPotSSHTransport,0,148.100.184.198] Te	rm	ina	l Size: 80 24
2023-11-27T23:37:36+0000	[twisted.conch.ssh.session#info] Getting shell			
2023-11-27T23:37:37+0000	[HoneyPotSSHTransport,0,148.100.184.198] CMD: ls			
2023-11-27T23:37:37+0000	[HoneyPotSSHTransport,0,148.100.184.198] Command found: ls			
2023-11-27T23:37:38+0000	[HoneyPotSSHTransport,0,148.100.184.198] CMD: clear			
2023-11-27T23:37:38+0000	[HoneyPotSSHTransport,0,148.100.184.198] Command found: clear			
2023-11-27T23:37:46+0000	[HoneyPotSSHTransport,0,148.100.184.198] CMD: cls			
2023-11-27T23:37:46+0000	[HoneyPotSSHTransport,0,148.100.184.198] Can't find command cls			
2023-11-27T23:37:46+0000	[HoneyPotSSHTransport,0,148.100.184.198] Command not found: cls			
2023-11-27T23:37:49+0000	[HoneyPotSSHTransport,0,148.100.184.198] Closing TTY Log: var/lib/cowrie/tty/12e1e0ffa70849362fc999e9	8	3000000000	b0e6bb4179609cc1bbdc0647a927c8b41a7 after 13 seconds
2023-11-27T23:37:49+0000	[HoneyPotSSHTransport,0,148.100.184.198] avatar root logging out			
2023-11-27T23:37:49+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#info] connection lost			
2023-11-27T23:37:49+0000	[HoneyPotSSHTransport,0,148.100.184.198] Connection lost after 17 seconds			
2023-11-28T00:36:45+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha1			
2023-11-28T00:36:45+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha256			
2023-11-28T00:36:45+0000	[cowrie.ssh.factory.CowrieSSHFactory] New connection: 198.235.24.158:54627 (172.17.0.2:2222) [session	:	0fc	c28d90ee8]
2023-11-28T00:36:45+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#info] connection lost			
2023-11-28T00:36:45+0000	[HoneyPotSSHTransport,1,198.235.24.158] Connection lost after 0 seconds			
2023-11-28T00:55:33+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha1			
2023-11-28T00:55:33+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha256			
2023-11-28T00:55:33+0000	[cowrie.ssh.factory.CowrieSSHFactory] New connection: 118.26.39.162:23890 (172.17.0.2:2222) [session:	5	0d7	f9944909]
2023-11-28T00:55:34+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha1			
2023-11-28T00:55:34+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha256			
2023-11-28T00:55:34+0000	[cowrie.ssh.factory.CowrieSSHFactory] New connection: 118.26.39.162:24076 (172.17.0.2:2222) [session:	3	d97	065b94b0]
2023-11-28T00:55:34+0000	[HoneyPotSSHTransport,3,118.26.39.162] Remote SSH version: SSH-2.0-Go			
2023-11-28T00:55:34+0000	[HoneyPotSSHTransport,3,118.26.39.162] SSH client hassh fingerprint: 2aec6b44b06bec95d73f66b5d30cb69a			
2023-11-28T00:55:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] kex alg=b'curve25519-sha256@libssh.org' key alg=b'e	cd	sa-	sha2-nistp256'
2023-11-28T00:55:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] outgoing: b'aes128-ctr' b'hmac-sha2-256' b'none'			
2023-11-28T00:55:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] incoming: b'aes128-ctr' b'hmac-sha2-256' b'none'			
2023-11-28T00:55:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] NEW KEYS			
2023-11-28T00:55:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#info] connection lost			
2023-11-28T00:55:34+0000	[HoneyPotSSHTransport,2,118.26.39.162] Connection lost after 0 seconds			
2023-11-28T00:55:49+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#info] connection lost			
2023-11-28T00:55:49+0000	[HoneyPotSSHTransport,3,118.26.39.162] Connection lost after 14 seconds			
2023-11-28T01:07:34+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha1			
2023-11-28T01:07:34+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha256			
2023-11-28T01:07:34+0000	[cowrie.ssh.factory.CowrieSSHFactory] New connection: 185.161.248.87:64001 (172.17.0.2:2222) [session	:	207	6945d06d0]
2023-11-28T01:07:35+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#info] connection lost			
2023-11-28T01:07:35+0000	[HoneyPotSSHTransport,4,185.161.248.87] Connection lost after 0 seconds			
2023-11-28T01:10:28+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha1			
2023-11-28T01:10:28+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha256			
2023-11-28T01:10:28+0000	[cowrie.ssh.factory.CowrieSSHFactory] New connection: 8.218.104.134:49464 (172.17.0.2:2222) [session:	9	3ce	7c4979c2]
2023-11-28T01:10:29+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#info] connection lost			
2023-11-28T01:10:29+0000	[HoneyPotSSHTransport,5,8.218.104.134] Connection lost after 0 seconds			
2023-11-28T01:10:33+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha1			
2023-11-28T01:10:33+0000	[cowrie.ssh.factory.CowrieSSHFactory] No moduli, no diffie-hellman-group-exchange-sha256			
2023-11-28T01:10:33+0000	[cowrie.ssh.factory.CowrieSSHFactory] New connection: 8.218.104.134:51260 (172.17.0.2:2222) [session:	b	38a	fe2a2197]
2023-11-28T01:10:33+0000	[HoneyPotSSHTransport,6,8.218.104.134] Remote SSH version: SSH-2.0-libssh_0.7.4			
2023-11-28T01:10:33+0000	[HoneyPotSSHTransport,6,8.218.104.134] SSH client hassh fingerprint: e37f354a101aff5871ba233aa82b84ec			
2023-11-28T01:10:33+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] kex alg=b'curve25519-sha256@libssh.org' key alg=b's	sh		25519'
2023-11-28T01:10:33+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] outgoing: b'aes256-ctr' b'hmac-sha2-256' b'none'			
2023-11-28T01:10:33+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] incoming: b'aes256-ctr' b'hmac-sha2-256' b'none'			
2023-11-28T01:10:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] NEW KEYS			
2023-11-28T01:10:34+0000	[cowrie.ssh.transport.HoneyPotSSHTransport#debug] starting service b'ssh-userauth'			
2023-11-28T01:10:34+0000	[cowrie.ssh.userauth.HoneyPotSSHUserAuthServer#debug] b'NL5xUDpV2xRa' trying auth b'publickey'			
2023-11-28T01:10:34+0000	[HoneyPotSSHTransport,6,8.218.104.134] Unhandled Error			
"	Traceback (most recent"	call last):			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/python/log.py"", line 96, in callWithLogger"			
"	    return callWithCont"	"ext({""system"": lp}, func, *args, **kw)"			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/python/log.py"", line 80, in callWithContext"			
"	    return context.call"	({ILogContext: newCtx}, func, *args, **kw)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/python/context.py"", line 117, in callWithContext"			
"	    return self.current"	Context().callWithContext(ctx, func, *args, **kw)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/python/context.py"", line 82, in callWithContext"			
"	    return func(*args,"	**kw)			
"	--- <exception caught h"	ere> ---			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/internet/posixbase.py"", line 482, in _doReadOrWrite"			
"	    why = selectable.do"	Read()			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/internet/tcp.py"", line 248, in doRead"			
"	    return self._dataRe"	ceived(data)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/internet/tcp.py"", line 253, in _dataReceived"			
"	    rval = self.protoco"	l.dataReceived(data)			
"	  File ""/cowrie/cowrie-"	"git/src/cowrie/ssh/transport.py"", line 144, in dataReceived"			
"	    self.dispatchMessag"	e(messageNum, packet[1:])			
"	  File ""/cowrie/cowrie-"	"git/src/cowrie/ssh/transport.py"", line 148, in dispatchMessage"			
"	    transport.SSHServer"	Transport.dispatchMessage(self, messageNum, payload)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/conch/ssh/transport.py"", line 800, in dispatchMessage"			
"	    self.service.packet"	Received(messageNum, payload)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/conch/ssh/service.py"", line 50, in packetReceived"			
"	    return f(packet)"				
"	  File ""/cowrie/cowrie-"	"git/src/cowrie/ssh/userauth.py"", line 72, in ssh_USERAUTH_REQUEST"			
"	    return userauth.SSH"	UserAuthServer.ssh_USERAUTH_REQUEST(self, packet)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/conch/ssh/userauth.py"", line 173, in ssh_USERAUTH_REQUEST"			
"	    d = self.tryAuth(me"	thod, user, rest)			
"	  File ""/cowrie/cowrie-"	"env/lib/python3.11/site-packages/twisted/conch/ssh/userauth.py"", line 148, in tryAuth"			
"	    ret = f(data)"				
